# Generated by Django 4.1 on 2022-08-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceSeq', models.CharField(max_length=32, verbose_name='序列号')),
                ('type', models.CharField(max_length=16, verbose_name='设备类型')),
                ('purchaseTime', models.DateField(verbose_name='设备购买时间')),
                ('state', models.SmallIntegerField(choices=[(0, '闲置'), (1, '已借出')], default=0, verbose_name='设备状态')),
            ],
        ),
    ]
