# Generated by Django 4.1 on 2022-08-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deviceID', models.IntegerField(max_length=7, verbose_name='设备ID')),
                ('applyPersonID', models.IntegerField(max_length=7, verbose_name='申请人ID')),
                ('applyPersonName', models.CharField(max_length=32, verbose_name='申请人姓名')),
                ('deviceSeq', models.CharField(max_length=32, verbose_name='序列号')),
                ('type', models.CharField(max_length=16, verbose_name='设备类型')),
                ('purchaseTime', models.DateField(verbose_name='设备购买时间')),
                ('applyTime', models.DateField(auto_now_add=True, verbose_name='申请时间')),
                ('state', models.SmallIntegerField(choices=[(0, '闲置'), (1, '已借出')], default=0, verbose_name='设备状态')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(default=None, max_length=32, verbose_name='密码')),
                ('job', models.CharField(max_length=32, verbose_name='职称')),
                ('phone_number', models.CharField(max_length=11, verbose_name='手机号码')),
                ('institution', models.CharField(max_length=64, verbose_name='所属支行')),
                ('power', models.SmallIntegerField(choices=[(0, '普通'), (1, '负责人'), (2, '管理员')], default=0, verbose_name='权限')),
            ],
        ),
    ]
