# Generated by Django 4.1 on 2022-08-09 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wangapp', '0004_remove_device_apply_state_device_apply_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_apply',
            name='institution',
            field=models.CharField(default=None, max_length=64, verbose_name='所属机构'),
        ),
        migrations.AlterField(
            model_name='device_apply',
            name='applyPersonID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wangapp.employee', verbose_name='申请人ID'),
        ),
        migrations.AlterField(
            model_name='device_apply',
            name='deviceID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wangapp.device', verbose_name='设备ID'),
        ),
    ]
