# Generated by Django 4.1 on 2022-08-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wangapp', '0007_alter_device_apply_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='state',
            field=models.SmallIntegerField(choices=[(0, '闲置'), (1, '已借出'), (2, '已借出')], default=0, verbose_name='设备状态'),
        ),
    ]
