# Generated by Django 4.1 on 2022-08-09 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wangapp', '0009_alter_device_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='device_applied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyPersonName', models.CharField(max_length=32, verbose_name='申请人姓名')),
                ('deviceSeq', models.CharField(max_length=32, verbose_name='序列号')),
                ('type', models.CharField(max_length=16, verbose_name='设备类型')),
                ('purchaseTime', models.DateField(verbose_name='设备购买时间')),
                ('applyTime', models.DateField(auto_now_add=True, verbose_name='申请时间')),
                ('institution', models.CharField(default=None, max_length=64, verbose_name='所属机构')),
                ('reason', models.TextField(default=None, verbose_name='理由')),
                ('state', models.SmallIntegerField(choices=[(0, '闲置'), (1, '审批中'), (2, '已借出')], default=0, verbose_name='设备状态')),
                ('applyPersonID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wangapp.employee', verbose_name='申请人ID')),
                ('deviceID', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wangapp.device', verbose_name='设备ID')),
            ],
        ),
    ]
